using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GunScript : MonoBehaviour
{
    public GameObject[] balaPrefab, balaPrefab2;
    public static int balaAtual;
    public static int whichWeapon = 1;
    public bool Ataque;
   

    void Start()
    {
       balaAtual = 0;
   
    }

    void Update()
    {
                if (Input.GetKeyDown(KeyCode.Tab))
                {
                    if (whichWeapon == 1)
                    {
                        whichWeapon = 2;
                    }
                    else
                    {
                        whichWeapon = 1;
                    }
                }

                if (Input.GetButtonDown("Fire1"))
                {

                    if (whichWeapon == 1)
                    {
                    
                GameObject b = Instantiate(balaPrefab[balaAtual],
                              transform.position, transform.rotation);
                
                Destroy(b.gameObject, 1.5f);
                       
            }

                    else
                    {
                        if (whichWeapon == 2)
                        {
                            Ataque = true;
                    
                    GameObject b = Instantiate(balaPrefab2[balaAtual],
                            transform.position, transform.rotation);
                    Ataque = false;
                    Destroy(b.gameObject, 1.5f);
                        
                }
                
            }
            

        }
   }


        }
    



